[phases.setup]
nixPkgs = ["nodePackages.npm", "nodejs"]

[phases.install]
cmds = ["cd frontend && npm install", "cd backend && npm install"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "node backend/server.js"
